robot-workers/csharp/RobotWorkers/RazorFrontend/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorFrontend.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

robot-workers/csharp/RobotWorkers/RazorFrontend/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace RazorFrontend.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly IHttpClientFactory _httpClientFactory;

    public IndexModel(IHttpClientFactory httpClientFactory, ILogger<IndexModel> logger)
    {
        _httpClientFactory = httpClientFactory;
        _logger = logger;
        ImageUrl =
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABaElEQVQ4jZ2TTUvDQBDGn3";
    }

    public string ImageUrl { get; set; }
    public string WorkerJson { get; set; }
    public RobotWorker Worker { get; set; }

    public async Task OnGetAsync()
    {
        await FetchDataAsync();
    }

    public async Task OnPostRefreshAsync()
    {
        await FetchDataAsync();
    }

    private async Task FetchDataAsync()
    {
        var httpClient = _httpClientFactory.CreateClient();

        var descriptionResponse = await httpClient.GetAsync("http://robot-worker-discovery:8080/worker");
        WorkerJson = await descriptionResponse.Content.ReadAsStringAsync();
        Worker = JsonSerializer.Deserialize<RobotWorker>(WorkerJson) ?? new RobotWorker();

        var robohashResponse =
            await httpClient.GetAsync("http://robohash-internal:8081/robohash/" +
                                      ComputeHashString(WorkerJson, 32));
        var imageStream = await robohashResponse.Content.ReadAsStreamAsync();
        var imageBytes = await ToByteArrayAsync(imageStream);
        ImageUrl = $"data:image/png;base64,{Convert.ToBase64String(imageBytes)}";
    }

    private static async Task<byte[]> ToByteArrayAsync(Stream stream)
    {
        using var memoryStream = new MemoryStream();
        await stream.CopyToAsync(memoryStream);
        return memoryStream.ToArray();
    }

    public static string ComputeHashString(string input, int length)
    {
        using var sha256 = SHA256.Create();
        var hashBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(input));
        var hashString = BitConverter.ToString(hashBytes).Replace("-", "").ToLower();

        return length >= hashString.Length ? hashString : hashString[..length];
    }
}

public class RobotWorker
{
    [JsonPropertyName("name")] public string Name { get; set; } = "Unknown";

    [JsonPropertyName("model")] public string Model { get; set; } = "Unknown";

    [JsonPropertyName("manufacturer")] public string Manufacturer { get; set; } = "Unknown";

    [JsonPropertyName("serialNumber")] public string SerialNumber { get; set; } = "Unknown";

    [JsonPropertyName("occupation")] public string Occupation { get; set; } = "Unknown";

    [JsonPropertyName("qualityRating")] public decimal QualityRating { get; set; } = 0;

    [JsonPropertyName("efficiencyRating")] public decimal EfficiencyRating { get; set; } = 0;

    [JsonPropertyName("pricePerHour")] public decimal PricePerHour { get; set; } = 0;
}

robot-workers/csharp/RobotWorkers/RazorFrontend/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorFrontend.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

robot-workers/csharp/RobotWorkers/RazorFrontend/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<style>
    .container {
        display: flex;
        align-items: center;
    }

    .text {
        flex: 0 0 60%;
        padding-right: 20px;
    }

    .image {
        flex: 0 0 40%;
        padding-right: 20px;
    }

    .image img {
        max-width: 100%;
        height: auto;
    }
</style>

<h1>Robot Worker @Model.Worker.Name</h1>
<div class="container">
    <div class="image">
        <img src="@Model.ImageUrl" alt="Robot Image"/>
    </div>

    <div class="text">
        <table>
            <thead>
            <tr>
                <th>Property</th>
                <th>Value</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>Name</td><td>@Model.Worker.Name</td>
            </tr>
            <tr>
                <td>Model</td><td>@Model.Worker.Model</td>
            </tr>
            <tr>
                <td>Manufacturer</td>
                <td>@Model.Worker.Manufacturer</td>
            </tr>
            <tr>
                <td>Serial number</td>
                <td>@Model.Worker.SerialNumber</td>
            </tr>
            <tr>
                <td>Occupation</td>
                <td>@Model.Worker.Occupation</td>
            </tr>
            <tr>
                <td>Quality rating</td>
                <td>@Model.Worker.QualityRating</td>
            </tr>
            <tr>
                <td>Efficiency rating</td>
                <td>@Model.Worker.EfficiencyRating</td>
            </tr>
            <tr>
                <td>Price per hour</td>
                <td>@Model.Worker.PricePerHour</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<form method="post">
    <button type="submit" asp-page-handler="Refresh">Refresh</button>
</form>

robot-workers/csharp/RobotWorkers/RazorFrontend/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RazorFrontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RazorFrontend.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">RazorFrontend</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - RazorFrontend - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>